# 1. 공통 기본 설정 (내 컴퓨터에서는 기본적으로 local 프로필 활성화)
spring:
  profiles:
    active: local

---
# 2. 내 컴퓨터(로컬) 전용 설정 -> H2 데이터베이스 사용
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:~/my-awesome-project;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true

---
# 3. Render(운영/도메인) 전용 설정 -> Render PostgreSQL 클라우드 DB 사용
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# 카카오페이 등 공통 API 설정
kakao:
  pay:
    admin-key: ${KAKAO_ADMIN_KEY:08ca6cf208732644b8bf804b540db9dd}
    cid: TC0ONETIME